import type { Metadata } from "next";

import "./globals.css";
import Header from "./components/Header";
import Footer from "./components/Footer";
import { fontPrimary } from "./fonts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    // TODO: add lang="vn" and lang="ru"
    <html lang="en">
      <body className={fontPrimary.className}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
